---

image: "quay.io/luzifer/repo-runner-image"
checkout_dir: /go/src/github.com/Luzifer/password

commands:
  - apk --update add zip 
  - git submodule update --init --recursive
  - make publish workflow

environment:
  CGO_ENABLED: 0
